[package]
name = "buffers-collections"
version = "0.1.0"
edition = "2021"

[dependencies]
buffers = { path = "../1_buffers", default-features = false }
test_utils = { path = "../a_test_utils" }

[features]
default = ["allocator", "array"]
allocator = ["buffers/allocator"]
array = ["buffers/array"]
